# Generated by Django 4.0.2 on 2022-10-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_into_servicio_alter_client_dni_alter_company_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.client'),
        ),
    ]
