# Generated by Django 4.0.2 on 2022-10-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_into_alter_client_dni_alter_company_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intoproduct',
            options={'default_permissions': (), 'ordering': ['id'], 'verbose_name': 'Detalle de Entrada', 'verbose_name_plural': 'Detalle de Entrada'},
        ),
        migrations.AddField(
            model_name='into',
            name='client',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='pos.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='into',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.company'),
        ),
    ]
