# Generated by Django 4.0.2 on 2022-10-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_cargo_client_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dni',
        ),
    ]
