# Generated by Django 4.0.2 on 2022-10-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_remove_into_iva_remove_into_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='into',
            name='client',
        ),
    ]
