# Generated by Django 4.0.2 on 2022-10-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_remove_into_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='into',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='into',
            name='requisicion',
            field=models.IntegerField(default=0, verbose_name='No_requisicion'),
        ),
    ]
