# Generated by Django 4.0.2 on 2022-10-26 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_remove_into_date_joined_into_requisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='into',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
