# Generated by Django 4.0.2 on 2022-10-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_alter_saleproduct_options_alter_into_requisicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='into',
            name='requisicion',
            field=models.IntegerField(null=True, verbose_name='No_requisicion'),
        ),
    ]
