# Generated by Django 4.0.2 on 2022-10-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_alter_into_requisicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_iva',
        ),
        migrations.AddField(
            model_name='sale',
            name='requisicion',
            field=models.IntegerField(null=True, verbose_name='No_requisicion'),
        ),
    ]
